### ISSUE TITLE
Cannot produce tfRecord files.

### ISSUE THREAD

**Issue by ehsan-soe** [asyml/texar#239] opened 2019-11-03 23:51 UTC
I tried using the ```prepare_data.py``` script to produce TFRecord_data for my own dataset where train/test/dev each has 4 separate files.
the train which is the biggest has ~78k instances (with max seq length of is 128).
However, it took for ever to be finish. 
It is stuck in this stage (processing the training files):
Note that the ```train.tf_record``` file is created in the output directory and has the size of 3.0M but it doesn't get updated and the size doesn't change after some point.
```
WARNING:tensorflow:From /home/Counterfactual-StoryRW/third_party/texar/texar/core/layers.py:629: The name tf.layers.Layer is deprecated. Please use tf.compat.v1.layers.Layer instead.

WARNING:tensorflow:From /home/Counterfactual-StoryRW/third_party/texar/texar/core/layers.py:682: The name tf.layers.MaxPooling1D is deprecated. Please use tf.compat.v1.layers.MaxPooling1D instead.

WARNING:tensorflow:From /home/Counterfactual-StoryRW/third_party/texar/texar/core/layers.py:683: The name tf.layers.AveragePooling1D is deprecated. Please use tf.compat.v1.layers.AveragePooling1D instead.

WARNING:tensorflow:From /home/Counterfactual-StoryRW/third_party/texar/texar/core/layers.py:1174: The name tf.layers.Conv1D is deprecated. Please use tf.compat.v1.layers.Conv1D instead.

WARNING:tensorflow:From /home/Counterfactual-StoryRW/third_party/texar/texar/core/layers.py:1175: The name tf.layers.Conv2D is deprecated. Please use tf.compat.v1.layers.Conv2D instead.

WARNING:tensorflow:From /home/Counterfactual-StoryRW/third_party/texar/texar/core/optimization.py:483: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

WARNING:tensorflow:From prepare_data_rewriting.py:48: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

WARNING:tensorflow:From prepare_data_rewriting.py:48: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

WARNING:tensorflow:From /home/Counterfactual-StoryRW/third_party/texar/texar/utils/utils_io.py:226: The name tf.gfile.IsDirectory is deprecated. Please use tf.io.gfile.isdir instead.

#examples: 77423
##train examples: 77423
WARNING:tensorflow:From /home/Counterfactual-StoryRW/utils/roc_data_utils_rewriting.py:220: The name tf.python_io.TFRecordWriter is deprecated. Please use tf.io.TFRecordWriter instead.
```

Any idea what I am doing wrong?
Thanks in advance

**Comment by gpengzhi** [comment] 2019-11-04 02:33
Hi, could you share your `prepare_data.py` script? What is the file structure of your dataset? What do you mean each has 4 separate files?

**Comment by Hannabrahman** [comment] 2019-11-04 03:18
> Hi, could you share your `prepare_data.py` script? What is the file structure of your dataset? What do you mean each has 4 separate files?

@gpengzhi Thanks for your reply. 
Actually I used the script [here](https://github.com/qkaren/Counterfactual-StoryRW/blob/master/prepare_data_rewriting.py). 

Then I modified the data_utils.py accordingly in [here](https://github.com/Hannabrahman/Counterfactual-StoryRW/blob/master/utils/roc_data_utils_rewriting.py). 

by 4 files I meant, the training dataset has 4 different part which I want to process them separately. The 4 files has the same length, it's just they are used in the model differently. The script [here](https://github.com/qkaren/Counterfactual-StoryRW/blob/master/prepare_data_rewriting.py) is doing the same thing and I could produce the tfRecord files with their data and code. But my data is a lot bigger and I am not sure if that is problem?

**Comment by Hannabrahman** [comment] 2019-11-04 05:06
@gpengzhi [This](https://github.com/Hannabrahman/Counterfactual-StoryRW/blob/master/utils/roc_data_utils_rewriting.py) is the data_utils

**Comment by ZhitingHu** [comment] 2019-11-04 18:02
It's hard to see where the problem is cuz the processing code was changed quite a lot.

* Could you create `dev.tf_record` and `test.tf_record` successfully? 
* Here is the for-loop processing each data instance. You may want to print the progress and see if the code is stuck at a certain instance

**Comment by Hannabrahman** [comment] 2019-11-05 06:55
> It's hard to see where the problem is cuz the processing code was changed quite a lot.
> 
>     * Could you create `dev.tf_record` and `test.tf_record` successfully?
> 
>     * [Here](https://github.com/Hannabrahman/Counterfactual-StoryRW/blob/master/utils/roc_data_utils_rewriting.py#L222) is the for-loop processing each data instance. You may want to print the progress and see if the code is stuck at a certain instance

> It's hard to see where the problem is cuz the processing code was changed quite a lot.
> 
>     * Could you create `dev.tf_record` and `test.tf_record` successfully?
> 
>     * [Here](https://github.com/Hannabrahman/Counterfactual-StoryRW/blob/master/utils/roc_data_utils_rewriting.py#L222) is the for-loop processing each data instance. You may want to print the progress and see if the code is stuck at a certain instance

Thanks @ZhitingHu I resolved the issue. The problem was coming from [here](https://github.com/qkaren/Counterfactual-StoryRW/blob/d16f8fb5ac7b829ad39d6c2afec4ab83dd1c0975/utils/data_utils_rewriting.py#L69), ```len(x1 + ' | ' + x3) ``` for some sample was already > max_seq_len and truncating x4 didn't help, so it was stuck in the while loop.

Thanks a lot, I am closing this.

**Closed** 2019-11-05 06:57 UTC
Labels: question
